### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by hgvhgv** [tuxor1337/dictmaster#4]
Hi thanks for this great script. Running into a small problem though:

`python2 dictmaster.py dwds --popts thirdparty/wordlists/deu/dwds.txt 5`

```
Traceback (most recent call last):
  File "dictmaster.py", line 59, in <module>
    main(parser.parse_args())
  File "dictmaster.py", line 24, in main
    plugin = load_plugin(args.plugin, args.popts, args.output)
  File "/home/hgv/work/git/dictmaster/dictmaster/util.py", line 47, in load_plugin
    pthread = plugin_module.Plugin(popts, dirname)
  File "/home/hgv/work/git/dictmaster/dictmaster/plugins/dwds.py", line 42, in __init__
    DWDSFetcher(self),
  File "/home/hgv/work/git/dictmaster/dictmaster/plugins/dwds.py", line 71, in __init__
    super(DWDSFetcher, self).__init__(plugin, threadcnt=10)
  File "/home/hgv/work/git/dictmaster/dictmaster/fetcher.py", line 69, in __init__
    self._queue = RawDbQueue(plugin.output_db)
  File "/home/hgv/work/git/dictmaster/dictmaster/queue.py", line 36, in __init__
    super(RawDbQueue, self).__init__()
  File "/home/hgv/work/git/dictmaster/dictmaster/queue.py", line 12, in __init__
    self._queue = Queue.Queue()
TypeError: 'module' object is not callable
```

Any thoughts?

I'm on Arch Linux 4.9.11-1.

**Comment by tuxor1337** [comment]
Is there another file or directory called Queue or Queue.py in your python path? I can't reproduce this with Python 2.7.12 on Ubuntu 16.04.

**Comment by tuxor1337** [comment]
On which file system are you executing this command? Maybe it's a case insensitive file system which might lead to problems with the (local) file `dictmaster/queue.py` being used to import the module `Queue` at some point.

**Comment by tuxor1337** [comment]
Note that the dwds plugin is defunct at the moment, see #5

**Comment by hgvhgv** [comment]
I think it's a case-sensitivity issue. I'm on HFS+ and share the drive between linux and mac, so it has to be case insensitive. So I guess I have to either figure out how to rename the local `dictmaster/queue.py` or specify to import `Queue` from python (right? there's only one Queue or Queue.py in my path, and it's [I believe] the correct one at /usr/lib/python2.7/Queue.py), or?

Learning as I go along, so I'll try to tinker until it comes out right (and while the dwds plugin gets redone—about which, thanks!).
